name: 'Install Maven'
description: 'Installs a specified version of Maven depending on the runner OS.'
inputs:
  maven-version:
    description: 'The Maven version to install.'
    required: true
    default: '3.9.6'

runs:
  using: "composite"
  steps:
    - name: Install Maven on Ubuntu
      if: runner.os == 'Linux'
      shell: bash
      run: |
        MAVEN_VERSION=${{ inputs.maven-version }}
        sudo apt-get update
        sudo apt-get install -y wget tar
        wget https://downloads.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
        sudo tar xzvf apache-maven-${MAVEN_VERSION}-bin.tar.gz -C /opt
        sudo ln -s /opt/apache-maven-${MAVEN_VERSION}/bin/mvn /usr/bin/mvn
        echo "Maven $MAVEN_VERSION installed on Ubuntu"

    - name: Install Maven on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $MavenVersion = '${{ inputs.maven-version }}'
        Invoke-WebRequest https://downloads.apache.org/maven/maven-3/$MavenVersion/binaries/apache-maven-$MavenVersion-bin.zip -OutFile apache-maven.zip
        Expand-Archive -Path apache-maven.zip -DestinationPath $Env:ProgramFiles\Maven
        $Env:Path += ";$Env:ProgramFiles\Maven\apache-maven-$MavenVersion\bin"
        echo "Maven $MavenVersion installed on Windows"

    - name: Install Maven on macOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        MAVEN_VERSION=${{ inputs.maven-version }}
        brew install maven@$MAVEN_VERSION
        echo "Maven $MAVEN_VERSION installed on macOS"

    - name: Verify Maven Installation
      shell: bash
      run: |
        mvn -version
